- name: autoupdate
  run: |
    # Скрипт для получения данных, например:
    curl -o data.txt https://f3dorovv14ykt.github.io/
- name: Check for changes
  run: |
    git config --global user.name "auto updater"
    git config --global user.email "auto-updater@example.com"
    git add data.txt
    git diff --cached --quiet || git commit -m "Update data from site"
- name: Push changes
  if: github.repository_owner == github.actor
  run: |
    git push
