name: Generate VLESS from Whitelist

on:
  push:
    paths:
      - 'data/whitelist.txt'
      - 'data/cidr.txt'
      - 'generator.py' # запуск при изменении самого скрипта
  workflow_dispatch: # возможность запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Разрешаем запись в репозиторий
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Generator Script
        run: |
          # Убедимся, что папка данных существует, чтобы скрипт не упал
          mkdir -p data configs
          python generator.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          
          git add configs/
          
          # Проверяем, есть ли изменения, чтобы не плодить пустые коммиты
          if ! git diff --staged --quiet; then
            git commit -m "Auto-generate: $(date +'%Y-%m-%d %H:%M') [Yakutsk]"
            git push
          else
            echo "Нет изменений для коммита"
          fi
